### ISSUE TITLE
How to make scrollbar dark?

### ISSUE THREAD

**Issue by mengxi-ream** [glideapps/glide-data-grid#1011]

**Comment by mengxi-ream** [comment]
Because it's vanilla html scrollbar. You can specify dark mode in css and scrollbar will be dark. In tailwind, it will be like
```css
@layer base {
  :root {
    color-scheme: dark;
  }
}
```
